# Generated by Django 5.2.7 on 2025-10-19 19:10

import django.db.models.deletion
import django.utils.timezone
import uuid
import wallet_stub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletStubAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('balance_pkr', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='WalletStubTx',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_tx_id', models.CharField(default=wallet_stub.models.gen_provider_tx_id, max_length=100, unique=True)),
                ('direction', models.CharField(max_length=10)),
                ('amount_pkr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('memo', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_stub.walletstubaccount')),
            ],
        ),
    ]
